---

  # [en_US] Time intervals configuration
  #
  # [pt_BR] Configurações de intervalos de tempo
  #
  time_intervals:
    # [en_US] Time interval for check if there are available heroes to work
    # Default value (in minutes): 10
    #
    # [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
    # Valor padrão (em minutos): 10
    send_heroes_for_work: 12
    
    # [en_US] Time interval to update heroes position in the map,
    # Default value (in minutes): 3
    #
    # [pt_BR] Intervalo de tempo para atualizar a posição dos heróis no mapa
    # Valor padrão (em minutos): 3
    refresh_heroes_positions: 3
    
    # [en_US] Time interval to check for new maps
    # Default value (in minutes): 5 
    #
    # [pt_BR] Intervalo de tempo para verificar por novos mapas
    # Valor padrão (em segundos): 5
    check_for_new_map_button: 5
    
    # [en_US] Time interval to check for captcha.
    # Default value (in minutes): 1
    #
    # [pt_BR] Intervalo de tempo para verificar se precisa resolver o captcha.
    # Valor padrão (em minutos): 1
    check_for_captcha: 0

    # [en_US] Time interval to check for login request
    # Default value (in minutes): 3
    #
    # [pt_BR] Intervalo de tempo para verificar se existe solicitação de login
    # Valor padrão (em minutos): 5
    check_for_login: 5

    # [en_US] Time interval between moviments
    # Default value (in seconds): 1 
    #
    # [pt_BR] Intervalo de tempo entre movimentos
    # Valor padrão (em segundos): 1
    interval_between_moviments: 1

  # [en_US] How confident the bot needs to be to click the buttons (values from 0 to 1. 0 is the minimum value, 1 is the maximum value)
  #
  # [pt_BR] O quão confiante o bot precisa estar para clicar nos botões (valores entre 0 e 1. 0 é o valor mínimo, 1 é o valor máximo)
  #
  threshold:
    # [en_US]
    # Default value: 0.7
    #
    # [pt_BR]
    # Valor padrão: 0.7
    default: 0.7

    # [en_US]
    # Default value: 0.8
    #
    # [pt_BR]
    # Valor padrão: 0.8
    commom: 0.8

    # [en_US]
    # Default value: 0.8
    #
    # [pt_BR]
    # Valor padrão: 0.8
    select_wallet_buttons: 0.8

    # [en_US]
    # Default value: 0.9
    #
    # [pt_BR]
    # Valor padrão: 0.9
    go_to_work_btn: 0.9

    # [en_US]
    # Default value: 0.9
    #
    # [pt_BR]
    # Valor padrão: 0.9
    green_bar: 0.9

  home:
    enable: False
    # If bot is sending the wrong hero home, make this number bigger.
    # if bot is not sending any hero home make this number smaller.
    hero_threshold: 0.90
    home_button_threshold: 0.95


  # [en_US]
  # Default value: 60
  #
  # [pt_BR]
  # Valor padrão: 60
  scroll_size: 60

# [en_US]
  # Default value: 3
  #
  # [pt_BR]
  # Valor padrão: 3
  scroll_attemps: 3

  # [en_US]
  # Default value: true
  #
  # [pt_BR]
  # Valor padrão: true
  use_click_and_drag_instead_of_scroll: true

  # [en_US]
  # Default value: 200
  #
  # [pt_BR]
  # Valor padrão: 200
  click_and_drag_amount: 200

  # [en_US]
  # Default value: green
  # Available options:
  # all   = select all heroes (regardless of the stamina bar)
  # green = select the heroes with green stamina bar (half or full)
  # full  = select only the heroes with full stamina bar
  #
  # [pt_BR]
  # Valor padrão: green
  # Opções disponíveis:
  # all   = seleciona todos os heróis (independente da barra de stamina)
  # green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
  # full  = seleciona somente os heróis com a barra de stamina cheia
  select_heroes_mode: "green"

  # [en_US] Option for save logs to a file (logs.txt)
  # Default value: False
  # Available options: False or True
  #
  # [pt_BR] Opção para salvar os logs em arquivo (logs.txt)
  # Valor padrão : False
  # Opções disponíveis: False ou True
  save_log_to_file: True

  # [en_US] Option for use multiples accounts on same monitor
  # Default value: False
  #
  # [pt_BR] Opção para usar multiplas contas no mesmo monitor
  # Valor padrão: False
  multiples_accounts_same_monitor:
    enable: False
    window_contains_title: 'bombcrypto'

  # [en_US] If you have macbook or laptop with Retina screen, enable this feature
  # Default value: False
  #
  # [pt_BR] Se você tem um macbook ou notebook com tela retina, habilite essa função
  # Valor padrão: False
  is_retina_screen: False

  scale_image:
    # [en_US] Enable for use different scale on your browser
    # Default value: False
    #
    # [pt_BR] Habilita para usar uma escala diferente de visão em seu navegador
    # Valor padrão: False 
    enable: False
    
    # [en_US] When enable scale, set what scale value used on your browser
    # Default value: 100
    #
    # [pt_BR] Quando a escala está habilitada, especificar o valor de escala utilizada em seu navegador
    # Valor padrão: 100 
    percent: 100

    # [en_US] When enable scale, set what scale images threshold to compare images
    # Default value: 0.9
    #
    # [pt_BR] Quando a escala está habilitada, especificar o valor de threshold para comparação de imagens
    # Valor padrão: 0.9 
    threshold: 0.9
