---
  time_intervals:
    send_heroes_for_work: 10 #min
    refresh_heroes_positions: 3 #min
    check_for_new_map_button: 3 #min
    check_for_login: 5 #min
    interval_between_moviments: 1 #s

  # how confident the bot needs to be to click the button 0-1
  trashhold:
    default: 0.7
    commom: 0.8
    select_wallet_buttons: 0.8
    go_to_work_btn: 0.9
    green_bar: 0.9

  scroll_size: 60
  use_click_and_drag_instead_of_scroll: true
  click_and_drag_amount: 200
  only_click_heroes_with_green_bar: true
  
